# ChatGPT
CHATGPT_API_KEY = "sk-TPv6zDBKBC9L0YgLE4NtYKXpPcR8rDjLL7Ex68JWoLMZz6tj"
# 腾讯AI绘图
TENCENT_SECRET_ID = "AKIDQgy4va0INEsIWWKuGNFxRhiVDhvvhEXd"
TENCENT_SECRET_KEY = "82iBPWO4XotlTyHMbeT3PYTZTIwPfjbG"
# 发邮件
EMAIL_HOST = "smtp.163.com"
SENDER = 'raymondli631@163.com'
EMAIL_KEY = 'XVWKWFDJUJMDUYPO'
